Fix clang format for newer versions
tesseract-robotics/tesseract_qt pull request #102
Opened 2024-02-23 19:51 UTC by smith-doug

This works for me with clang-format-14 on 22.04

After https://github.com/tesseract-robotics/tesseract_qt/pull/101

2024-02-25 22:23 UTC, Levi-Armstrong commented
Can we pin it to the highest version available on  20.04?

2024-02-26 07:07 UTC, rjoomen commented on .clang-format
> +    AfterCaseLabel : 'true'
Can you put this before AfterClass, so the list is sorted?

2024-02-26 07:10 UTC, rjoomen commented
LGTM, I've been using this for a while already with a recent clang-tidy.

2024-02-26 15:37 UTC, Levi-Armstrong commented
It looks like you can install version 14 on 20.04 so I would just pin the scripts to version 14. This way it forces every one to use the desired version.

2024-02-26 15:37 UTC, Levi-Armstrong requested changes

2024-02-26 15:37 UTC, Levi-Armstrong commented on .run-clang-format
> +find . -type f -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\|hxx\)' -exec clang-format -style=file -i {} \;
Update to clang-format-14

2024-02-26 22:30 UTC, smith-doug commented
Sorry if I notified the wrong person.  I haven't used the review features on github much.  Both changes were made.

2024-02-26 23:42 UTC, Levi-Armstrong approved these changes

2024-02-26 23:48 UTC, merged