Make build of rendering and studio modules optional
tesseract-robotics/tesseract_qt pull request #70
Opened 2023-08-14 17:41 UTC by marip8

Per the title, this PR makes the build of the studio and rendering modules optional to allow users to skip the cumbersome build/install of `gz` and the Qt advanced docking repository

2023-08-15 13:21 UTC, Levi-Armstrong requested changes

2023-08-15 13:21 UTC, Levi-Armstrong commented on plot/CMakeLists.txt
> +find_package(qtadvanceddocking QUIET)
What about making this enabled based on BUILD_STUDIO? This component was primary added for studio use.

2023-08-15 13:21 UTC, Levi-Armstrong commented on plot/CMakeLists.txt
> +  list(APPEND SOURCES src/plot_docker.cpp)
Should these parameters be prefixed with `PLOT_`?

2023-08-15 13:21 UTC, Levi-Armstrong commented on srdf/CMakeLists.txt
> +set(TARGETS ${PROJECT_NAME}_srdf)
It may be better to choose something unique because I am not sure how CMake handles name conflicts.

2023-08-15 13:25 UTC, marip8 commented on plot/CMakeLists.txt
> +find_package(qtadvanceddocking QUIET)
I wasn't sure about this one since it was in the plot module. Would it make more sense to move this to the studio module instead?

2023-08-16 14:39 UTC, Levi-Armstrong commented on plot/CMakeLists.txt
> +find_package(qtadvanceddocking QUIET)
I think that would be fine, maybe move this to common directory

2023-08-16 14:48 UTC, marip8 commented on plot/CMakeLists.txt
> +find_package(qtadvanceddocking QUIET)
My goal here is to avoid building things that depend on `qtadvanceddocking` and `gz`, so moving this file to common would require me to do the same `find_package(qtadvanceddocking QUIET)` as here. I think it makes more sense to move it to studio instead since they share the dependency on `qtadvanceddocking`

2023-08-16 14:50 UTC, Levi-Armstrong commented on plot/CMakeLists.txt
> +find_package(qtadvanceddocking QUIET)
Sorry, we were already talking about moving it to studio so I was talking about moving it to the studio/common directory.

2023-08-16 15:12 UTC, marip8 commented on CMakeLists.txt
> +endif()
Does the studio module depend on the rendering module? It doesn't seem like it, but I can't quite tell

2023-08-16 15:14 UTC, marip8 commented on CMakeLists.txt
> +endif()
I see that studio links against `${PROJECT_NAME}_render_widgets`, which comes from the rendering module; so yes

2023-08-17 15:44 UTC, Levi-Armstrong approved these changes

2023-08-17 15:44 UTC, merged